### PR TITLE
Consistency and suggestions.

### PR DESCRIPTION
**Pull request by shockpast**

### CODE REVIEW

**Comment by shockpast** [comment]
Aren't the `xpcall` better than `pcall`? (atleast with supporting custom error logs)
изображение

**Comment by shockpast** [comment]
`sanct`?
изображение

**Comment by shockpast** [comment]
lblAvailable got Color(150, 255, 150, **255**)
изображение

But then, why lblLoadout didn't got Color(193, 202, 255, **255**)?
изображение

**Comment by shockpast** [comment]
`CLoadout.PrintF()`?
изображение

**Comment by shockpast** [comment]
изображение

**Comment by StyledStrike** [comment]
> Aren't the `xpcall` better than `pcall`?

Oh weapons are coming from clients, this is more of a way to validate that the weapon class exists, not to debug. 

> `sanct`?

This addon was initially made for Sanctuary sandbox. The name was kept for backwards compatibility.

> lblAvailable got Color(150, 255, 150, **255**)

I forgot 💀

> `CLoadout.PrintF()`?

`PrintF` only prints to console, but I needed to let the player know. Hmm actually, a better way would be to create a similar function but that prints to the player's chat instead...

About the commits, nice work! Thx

**Comment by StyledStrike** [comment]
I just realized I had "Custom Chat" on `PrintF`... Thats a lil embarrassing...

**Pull request merged**
